services:
  sss:
    image: cppla/serverstatus:latest
    container_name: serverstatus
    restart: unless-stopped
    volumes:
      - ./config.json:/ServerStatus/server/config.json 
      - ./json:/usr/share/nginx/html/json
    ports:
      - 35601:35601
      - 35602:80 
  bot:
    image: serverstatus-bot4sss  # 使用已经手动构建的镜像
    container_name: serverstatus-bot4sss
    restart: unless-stopped
    environment:
      - TG_CHAT_ID=tg_chat_id
      - TG_BOT_TOKEN=tg_bot_token
